// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "ryanliu6.xyz",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d44lozkj1nb91.cloudfront.net"
};


export default awsmobile;
